version: "3"
services:
  db:
    image: mysql:latest
    container_name: local-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=babi123
      - MYSQL_DATABASE=mysqlgo
    volumes:
      - /Users/dwikicahyo/Documents/code/post-go/db:/var/lib/mysql
